       IDENTIFICATION DIVISION.
       PROGRAM-ID. HW09EVNB.
      * ASK USED FOR ROCK, PAPER OR SCISSORS.
      * COMPARE THEIR INPUT ANSWER TO THE RANDOM NUMBER
      * GENERATED BY THE PROGRAM.  PROVIDE WINNER/LOSER FEEDBACK. 
       AUTHOR. NIKOLINA BEST.
       DATE-WRITTEN. 03/11/18.

       data division.
       working-storage section.
       01  WS-TODAYS-DATE          pic x(08).
       01  WS-TIME.
           05 WS-TIME-HH           pic 9(02).
           05 WS-TIME-MM           PIC 9(02).
           05 WS-TIME-SS           PIC 9(02).
           05 WS-TIME-MS.
              10 WS-TIME-MS1       PIC 9(01).
              10 WS-TIME-MS2       PIC 9(01).
                 88 RANDOM-ROCK              VALUE 0 1 2.     
                 88 RANDOM-PAPER             VALUE 3 4 5.
                 88 RANDOM-SCISSORS          VALUE 6 7 8.
                 88 VALID-RANDOM-DIGIT       VALUE 0 THRU 8.
                    
       01 WS-CHOICE                PIC X(01).
          88 ROCK-CHOSEN                     VALUE 'R' 'r'.
          88 PAPER-CHOSEN                    VALUE 'P' 'p'.
          88 SCISSORS-CHOSEN                 VALUE 'S' 's'.
          88 VALID-CHOICE                    VALUE 'R' 'r'
                                                   'P' 'p'
                                                   'S' 's'
                                                   'X' 'x'
                                                   'Q' 'q'.
          88 EXIT-CHOICE                     VALUE 'X' 'x'
                                                   'Q' 'q'.
       PROCEDURE DIVISION.
       0000-MAINLINE.
           DISPLAY 'START RPSGAMFL BY NIKOLINA BEST'.
           ACCEPT WS-TODAYS-DATE from date yyyymmdd.
           DISPLAY "PROGRAM EXECUTION DATE      : " WS-TODAYS-DATE.
           ACCEPT WS-TIME from time.
           DISPLAY "PROGRAM EXECUTION START TIME: " WS-TIME.
           DISPLAY "R FOR ROCK, P FOR PAPER, S FOR SCISSORS"
           DISPLAY "ENTER X OR Q TO EXIT"
        
      * PROMPT THE USER FOR GAME CHOICE UNTIL A VALID CHOICE IS MADE. 
           PERFORM UNTIL EXIT-CHOICE
               PERFORM 1000-SET-RANDOM-NUMBER
               ACCEPT WS-CHOICE
               PERFORM 2000-DISPLAY-RANDOM-SELECTION
               PERFORM 3000-SHOW-USER-SELECTION
               PERFORM 4000-DETERMINE-WINNER
           END-PERFORM.
           GOBACK.

       1000-SET-RANDOM-NUMBER.
      * QUASI-RANDOM NUMBER GENERATOR FOR GAME    
           MOVE 9 TO WS-TIME-MS2.
           PERFORM UNTIL VALID-RANDOM-DIGIT
             ACCEPT WS-TIME from time
           END-PERFORM.

       2000-DISPLAY-RANDOM-SELECTION.
           EVALUATE TRUE
               WHEN RANDOM-ROCK DISPLAY "COMPUTER CHOSE ROCK"
               WHEN RANDOM-PAPER DISPLAY "COMPUTER CHOSE PAPER"
               WHEN OTHER DISPLAY "COMPUTER CHOSE SCISSORS"
           END-EVALUATE.

       3000-SHOW-USER-SELECTION.
           EVALUATE TRUE
               WHEN ROCK-CHOSEN DISPLAY "YOU CHOSE ROCK"
               WHEN PAPER-CHOSEN DISPLAY "YOU CHOSE PAPER"
               WHEN EXIT-CHOICE DISPLAY "YOU HAVE OPTED OUT"
               WHEN OTHER DISPLAY "YOU CHOSE SCISSORS"
           END-EVALUATE.

           

       4000-DETERMINE-WINNER.
           EVALUATE TRUE 
               WHEN VALID-CHOICE
                   EVALUATE TRUE ALSO TRUE
                       WHEN RANDOM-ROCK ALSO ROCK-CHOSEN
                           DISPLAY "YOU HAVE TIED"
                       WHEN RANDOM-ROCK ALSO PAPER-CHOSEN
                           DISPLAY "PAPER COVERS ROCK - PAPER WINS "
                             "ROCK LOSES"
                           DISPLAY "YOU WIN!"
                       WHEN RANDOM-ROCK ALSO SCISSORS-CHOSEN
                           DISPLAY "ROCK CRUSHES SCISSORS - ROCK WINS, "
                             "SCISSORS LOSES"
                           DISPLAY "YOU LOSE!"
                   END-EVALUATE
                   EVALUATE TRUE ALSO TRUE
                       WHEN RANDOM-PAPER ALSO PAPER-CHOSEN
                           DISPLAY "YOU HAVE TIED"
                       WHEN RANDOM-PAPER ALSO ROCK-CHOSEN
                           DISPLAY "PAPER COVERS ROCK - PAPER WINS "
                             "ROCK LOSES"
                           DISPLAY "YOU LOSE!"
                       WHEN RANDOM-PAPER ALSO SCISSORS-CHOSEN
                           DISPLAY "SCISSORS CUT PAPER - SCISSORS WINS,"
                             " PAPER LOSES"
                           DISPLAY "YOU WIN!"
                   END-EVALUATE
                   EVALUATE TRUE ALSO TRUE 
                       WHEN RANDOM-SCISSORS ALSO SCISSORS-CHOSEN
                           DISPLAY "YOU HAVE TIED"
                       WHEN RANDOM-SCISSORS ALSO PAPER-CHOSEN
                           DISPLAY " SCISSORS CUTS PAPER - SCISSORS"
                                   " WINS, PAPER LOSES"
                           DISPLAY "YOU LOSE!"
                       WHEN RANDOM-SCISSORS ALSO ROCK-CHOSEN
                           DISPLAY "ROCK CRUSHES SCISSORS - ROCK WINS, "
                             "SCISSORS LOSES"
                           DISPLAY "YOU WIN!"
                   END-EVALUATE
           END-EVALUATE.

           EVALUATE FALSE 
               WHEN VALID-CHOICE
                   DISPLAY "PLEASE ENTER A VALID CHOICE"
           END-EVALUATE.
